name: Run Gradle Build

on:
  pull_request:
       branches:
         - main

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: [gradle]
    steps:
    - name: JUnit Test Run
      run: ./gradlew build

  test-report:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: JUnit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JUnit Tests            # Name of the check run which will be created
          path: /app/build/test-results/testReleaseUnitTest/*.xml    # Path to test results
          reporter: java-junit        # Format of test results