name: Run App Build

on:
  pull_request:
       branches:
         - main
  push:
    branches:
      - main
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    name: Run JUnit Test
    needs: [gradle]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: JUnit Test Run
        run: ./gradlew build

      - name: JUnit Test Report
        uses: dorny/test-reporter@v1
        with:
         name: JUnit Tests            # Name of the check run which will be created
         path: ./app/build/test-results/testReleaseUnitTest/*.xml    # Path to test results
         reporter: java-junit